ENH: Extend rmANOVA analysis script to subsampling experiments
Extend rmANOVA analysis script to subsampling experiments.

Specifically, filter data from participants that are not present across
all experiments. Some participants did not have the required number of
diffusion sensitizing directions, and thus were not included in the
subsampling experiments. Rm ANOVA requires data across experiments to
have the same number of observations and subjects, otherwise it raises
the error:
```
  File "lib/python3.8/site-packages/statsmodels/stats/anova.py", line 505, in __init__
    self._check_data_balanced()
  File "lib/python3.8/site-packages/statsmodels/stats/anova.py", line 541, in _check_data_balanced
    raise ValueError(error_message)
ValueError: Data is unbalanced.
```

Add the accompanying shell script.